---
title: "R Notebook"
output: html_notebook
---

```{r}
library(reshape2)
library(ggplot2)
```


```{r}
df <- read.csv("SpotifyFeaturesPreprocessed.csv")
```


```{r}
trainingSize <- floor(0.9 * nrow(df))
set.seed(123)
trainingIndex <- sample(seq_len(nrow(df)), size = trainingSize)
training <- df[trainingIndex, ]
testing <- df[-trainingIndex, ]
```

```{r}

spotifyCorMat = cor(df, use = "pairwise.complete.obs")

# get_lower_tri(), get_upper_tri, and plotCorMat() were adapted from:
# http://www.sthda.com/english/wiki/ggplot2-quick-correlation-matrix-heatmap-r-software-and-data-visualization

get_lower_tri<-function(cormat){
  cormat[upper.tri(cormat)] <- NA
  return(cormat)
}

get_upper_tri <- function(cormat){
  cormat[lower.tri(cormat)]<- NA
  return(cormat)
}

plotCorMat <- function(data, title){
  data <- round(data, digits = 2)
  dd <- as.dist((1-data)/2)
  hc <- hclust(dd)
  data <-data[hc$order, hc$order]
  upper_tri <- get_upper_tri(data)
  melted_data <- melt(upper_tri, na.rm = TRUE)
  ggheatmap <- ggplot(melted_data, aes(Var2, Var1, fill = value))+
    geom_tile(color = "white")+
    scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
    midpoint = 0, limit = c(-1,1), space = "Lab", 
    name=title) +
    theme_minimal()+ # minimal theme
    theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 12, hjust = 1))+
    coord_fixed()
  print(ggheatmap + 
          geom_text(aes(Var2, Var1, label = value), color = "black", size = 4) +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.grid.major = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank(),
    axis.ticks = element_blank(),
    legend.justification = c(1, 0),
    legend.position = c(0.6, 0.7),
    legend.direction = "horizontal")+
    guides(fill = guide_colorbar(barwidth = 7, barheight = 1,
      title.position = "top", title.hjust = 0.5))
    )
}

plotCorMat(spotifyCorMat, "Spotify\nCorrelation Matrix")

```

```{r}

regression <- lm(popularity ~ acousticness + loudness + danceability + energy + instrumentalness + liveness + speechiness, data=as.data.frame(training))


cat("regression RMSE: $", sqrt(mean(regression$residuals^2)), "\n")

# fill in any empty values with zeros, and use regression4 to predict on the test set

testing[is.na(testing)] <- 0
prediction <- predict.lm(regression, as.data.frame(testing))

# calculate RMSE of regression4 on the test set

totalSquaredError <- 0
for (i in 1:3160) {
  totalSquaredError <- totalSquaredError + abs(prediction[i] - testing[i, "popularity"])^2

}

testingRMSE <- sqrt(totalSquaredError / 3160)
cat("regression test set RMSE: ", testingRMSE)
```
